In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('F:/TensorFlow/xinjiang/traindata20230307.csv',header=0,encoding='utf_8')
df.info()
df.className.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 903 entries, 0 to 902
Columns: 295 entries, className to Y
dtypes: float64(17), int64(277), object(1)
memory usage: 2.0+ MB

array(['白茎绢蒿荒漠', '早熟禾草甸', '芦苇盐生草甸', '寸草苔草甸（1:100图，薹草、杂类草草甸）', '芦苇草甸',
       '羊茅草原', '盐生假木贼荒漠', '克氏针茅草原', '膜果麻黄荒漠', '含盐生半灌木的芦苇盐生草甸', '合头草荒漠',
       '针茅草原', '其它嵩草草甸', '其它薹草草甸', '紫花针茅草原', '早熟禾杂类草草甸', '芦苇盐生草甸（含盐生半灌木）',
       '盐生草荒漠', '木本猪毛菜荒漠', '蒿叶猪毛菜荒漠', '驼绒藜荒漠', '新疆银穗草草原', '蒿属荒漠', '小蓬荒漠',
       '戈壁藜荒漠', '沙生针茅荒漠草原', '麻黄荒漠', '梭梭荒漠', '短叶假木贼荒漠', '枇杷柴荒漠', '霸王荒漠',
       '含多枝柽柳的花花柴盐生草甸', '疏叶骆驼刺盐生草甸', '冷蒿荒漠草原', '柽柳灌丛', '多枝柽柳荒漠',
       '含多枝柽柳的芦苇盐生草甸', '花花柴盐生草甸', '裸地', '沙拐枣属荒漠', '猪毛菜属荒漠', '芨芨草草原',
       '旱蒿荒漠', '短花针茅荒漠草原', '镰芒针茅矮半灌木荒漠草原', '芨芨草草甸', '小针茅荒漠草原',
       '薹草、珠芽蓼高寒草甸', '高山嵩草高寒草甸', '草原苔草、杂类草草甸草原', '线叶嵩草草甸', '短花针茅典型草原',
       '杂类草高寒草甸', '高山绢蒿荒漠', '紫花针茅、新疆银穗草草原', '柽柳属荒漠', '绢蒿属荒漠',
       '昆仑针茅、高山绢蒿荒漠草原', '新疆银穗草、穗状寒生羊茅荒漠草原', '镰芒针茅荒漠草原', '人工草地',
       '早熟禾、羽衣草草甸', '鸭茅草甸', '羊茅、杂类草草甸草原', '锦鸡儿、镰芒针茅荒漠草原'], dtype=object)

In [4]:
df = df.loc[:,['className','PR2018','PR2019','PR2020','PR2021']]
df

      className    PR2018    PR2019     PR2020     PR2021
0        白茎绢蒿荒漠  0.340475  0.314325  13.083333  16.500000
1        白茎绢蒿荒漠  0.342047  0.305708  13.500000  16.666667
2        白茎绢蒿荒漠  0.383851  0.345391  13.250000  16.333333
3         早熟禾草甸  0.334299  0.349225  19.166667  19.583333
4        芦苇盐生草甸  0.340365  0.334513  11.666667  13.166667
..          ...       ...       ...        ...        ...
898   早熟禾、羽衣草草甸  0.627295  0.546654  34.166667  35.833333
899  羊茅、杂类草草甸草原  0.584332  0.535213  25.166667  26.416667
900        针茅草原  0.584332  0.535213  26.000000  27.166667
901       早熟禾草甸  0.334299  0.349225  20.583333  20.500000
902        蒿属荒漠  0.288966  0.245946  10.333333  12.250000

[903 rows x 5 columns]

In [6]:
result = df.groupby('className').agg({'PR2018':'mean','PR2019':'mean','PR2020':'mean','PR2021':'mean'})
result.head()

             PR2018    PR2019     PR2020     PR2021
className
人工草地       0.427161  0.390063  17.291667  16.972222
克氏针茅草原     0.380379  0.305449  20.261905  19.845238
其它嵩草草甸     0.330673  0.399824  23.539216  22.274510
其它薹草草甸     0.347056  0.437712  23.277778  21.587963
冷蒿荒漠草原     0.269482  0.276530  17.142857  14.571429

In [7]:
result.to_csv("xinjiang_veg_prep.csv")