In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv('F:/TensorFlow/traindata20220126.csv',header=0,encoding='utf_8')
df.info()
df.ClassName.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17211 entries, 0 to 17210
Columns: 257 entries, ClassName to Wgs84Y
dtypes: float64(26), int64(230), object(1)
memory usage: 33.7+ MB

array(['荒漠', '膜果麻黄（Ephedra przewalskii）荒漠', '盐爪爪（Kalidium foliatum）荒漠',
       '芨芨草（Achnatherum splendens）草甸', '矮生嵩草（Kobresia humilis）草甸',
       '垂穗披碱草（Elymus nutans）高寒草甸', '高山嵩草（Kobresia pygmaea）草甸',
       '高山薹草（Carex pseudosupina）草原', '紫花针茅（Stipa purpurea）草原',
       '早熟禾、垂穗披碱草高寒草甸', '线叶嵩草（Kobresia capillifolia）草甸',
       '金露梅（Potentilla fruticosa）灌丛', '鹅绒委陵菜（Potentilla anserina）高寒草甸',
       '垫状金露梅（Potentilla fruticosa var. pumila）灌丛',
       '藏北嵩草（Kobresia littledalei）沼泽草甸', '细叶嵩草（Kobresia filifolia）草甸',
       '扇穗茅（Littledalea racemosa）高寒草原',
       '藏嵩草（Kobresia vchaenoides=Kobresia tibetica）沼泽草甸',
       '青藏薹草（Carex moorcroftii）高寒草原', '嵩草（Kobresia spp.）草甸',
       '冰草（Agropyron cristatum）草原', '短花针茅（Stipa breviflora）荒漠草原',
       '芨芨草（Achnatherum splendens）草原', '赖草（Leymus secalinus）草甸',
       '长芒草（Stipa bungeana）草原', '沙生针茅（Stipa glareosa）荒漠草原',
       '华扁穗草（Blysmus sinocompressus）沼泽化草甸', '羊茅（Festuca ovina）杂类草草甸',
       '糙喙薹草（Carex scabrirostris）草甸', '小叶金露梅（Potentilla parvifolia）灌丛',
       '黄帚橐吾（Ligularia virgaurea）杂类草草甸',
       '圆穗蓼（Polygonum macrophyllum）、珠芽蓼（Polygonum viviparum）高寒草甸',
       '高山稀疏植被', '细叶西伯利亚蓼（Polygonum sibiricum var. thomsonii）杂类草草甸',
       '细叶亚菊（Ajania tenuifolia）草原', '冷蒿（Artemisia frigida）草原',
       '薹草、嵩草高寒草甸与匍匐水柏枝灌丛（专为植被图）',
       '沙生风毛菊（Saussurea arenaria）＋矮风毛菊（Saussurea humilis）高寒草甸',
       '异针茅（Stipa aliena）草原', '三芒草（Aristida adscensionis）草甸',
       '山生柳（Salix oritrepha）灌丛', '细叶亚菊（Ajania tenuifolia）杂类草草甸',
       '黄花枇杷柴（Reaumurea trigyna）荒漠', '圆叶盐爪爪（Kalidium schrenkianum）荒漠',
       '驼绒藜（Ceratoides latens）荒漠', '合头草（Sympegma regelii）荒漠',
       '猫头刺（Oxytropis aciphylla）荒漠', '西藏亚菊（Ajania tibetica）荒漠',
       '芦苇（Phragmites australis）盐生草甸', '芦苇（Phragmites australis）沼泽',
       '多花柽柳（Tamarix hohenackeri）荒漠', '蒿叶猪毛菜（Salsola abrotanoides）荒漠',
       '梭梭（Haloxylon ammondendron）荒漠', '胡杨（Populus euphratica）林',
       '疏花针茅（Stipa penicillata）草原',
       '青海早熟禾（Poa rossbergiana）+扇穗茅（Littledalea racemosa）高寒草甸',
       '藏沙蒿（Artemisia wellbyi ）高寒草原',
       '光沙蒿（Artemisia oxycephala=沙蒿Artemisia arenaria）荒漠',
       '狭叶锦鸡儿（Caragana stenophylla ）荒漠草原', '柽柳（Tamarix spp.）荒漠',
       '芨芨草（Achnatherum splendens）+驼绒藜（Krascheninnikovia ceratoides）荒漠草原',
       '青海刺参（Morina kokonorica）草原',
       '头花杜鹃（Rhododendron capitatum）＋百里香杜鹃（Rh. thimifolium）灌丛',
       '冰岛蓼（Koenigia islandica）草甸', '黑穗薹草（Carex atrata）草甸',
       '甘肃雪灵芝、垫状点地梅、簇生柔籽草垫状植被', '青海早熟禾（Poa rossbergiana）草甸',
       '黄缨菊（Xanthopappus subacaulis）、狼毒（Stellera\xa0chamaejasme）草原化草甸',
       '青扦（Picea wilsonii）林', '马蔺（Iris lactea var. chinensis）草甸',
       '鬼箭锦鸡儿（Caragana jubata）灌丛',
       '圆叶盐爪爪（Kalidium schrenkianum）、芨芨草（Achnatherum splendens）草原',
       '风毛菊（Saussurea spp.）+红景天（Rhodiola spp.）+垂头菊（Cremanthodium spp.）群落（专为植被制图）',
       '藓状雪灵芝（Arenaria bryophylla）垫状植被', '农田作物', '草地早熟禾（Poa pratensis）草甸',
       '人工草地', '青海云杉（Picea crassifolia）林', '山杨（Populus davidiana）林',
       '红桦（Betula albo-sinensis）林', '肋果沙棘（Hippophae neurocarpus）灌丛',
       '白桦（Betula platyphylla）林', '鲜卑花、黄花垫柳、金露梅灌丛',
       '西北针茅（Stipa sareptana var. krylovii）草原',
       '细叶早熟禾（Poa pratensis subsp. angustifolia）草甸草原',
       '矮生忍冬（Lonicera rupicola var. minuta ）杂类草草甸',
       '高山柳（Salix cupularis）灌丛', '硬叶柳（Salix sclerophylla）灌丛',
       '薹草（Carex spp.）草甸', '醉马草（Achnatherum inebrians）草原',
       '中亚早熟禾（Poa litwinowiana）高寒草原', '白莲蒿（Artemisia stechmanniana）草原',
       '毛枝山居柳（Salix oritrepha）灌丛', '方枝圆柏（Juniperus saltuaria）林',
       '青海固沙草（Orinus kokonorica）高寒草原', '薹状蚤缀与垫状点地梅垫状植被',
       '西北针茅、矮生嵩草（Kobresia humilis）草甸', '西藏沙棘（Hippophae tibetana）灌丛',
       '唐古特红景天（Rhodiola algida var. tangutica）荒漠',
       '匍匐水柏枝（Myricaria prostrata）灌丛',
       '白桦（Betula platyphylla）+山杨（Populus davidiana）林',
       '雪岭云杉（Picea schrenkiana）林', '圆柏灌丛',
       '华北落叶松（Larix principis-rupprechtii）+青扦（Picea wilsonii）+白扦（Picea meyeri）混交林',
       '三裂碱毛茛（Halerpestes tricuspis）沼泽', '大针茅（Stipa grandis）草原',
       '青藏薹草（Carex moorcroftii）+垫状驼绒藜（Krascheninnikovia compacta）高寒荒漠草原',
       '暗褐薹草（Carex atrofusca）草甸', '黑穗画眉草（Eragrostis nigra）沼泽化草甸',
       '铺地小叶金露梅（Potentilla parrifolia ）灌丛',
       '水栒子（Cotoneaster\xa0multiflorus）灌丛', '克氏针茅（Stipa kryllovii）草原',
       '碱韭（Allium polyrhizum）草原', '羊草（Leymus chinensis）草原',
       '隐子草（Cleistogenes spp.）草原',
       '羽柱针茅（Stipa subsessiliflora var. basiplumosa）草原',
       '粗壮嵩草（Kobresia robusta ）草甸',
       '烈香杜鹃（Rhododendron anthopogonoides）灌丛',
       '大花嵩草（Kobresia macrantha）草甸', '杂类草草甸', '高山柏（Juniperus squamata）灌丛',
       '毛瓣棘豆（Oxytropis sericopetala）草原', '昆仑蒿（Artemisia nanschanica）草原',
       '镰叶韭（Allium carolinianum）草原', '毛莲蒿（Artemisia vestita）草原',
       '雪层杜鹃（Rhododendron nivale）灌丛', '高山杜鹃（Rhododendron lapponicum）灌丛',
       '大花蒿（Artemisia macrocephala）草原', '大籽蒿（Artemisia sieversiana）草原',
       '展苞灯心草（Juncus thomsonii）草甸', '弱小火绒草(Leontopodium pusillum)草原',
       '硬毛棘豆（Oxytropis fetissovii ）草原', '束伞亚菊（Ajania parviflora）荒漠',
       '马先蒿（Pedicularis spp.）草甸', '藏羊茅（Festuca wallichiana）草原',
       '吉拉柳（Salix gilashanica）灌丛', '刚毛忍冬（Lonicera hispida）灌丛',
       '窄叶鲜卑花（Sibiraea angustata）灌丛', '金花小檗（Berberis wilsoniae）灌丛',
       '牛皮消（Cynanchum auriculatum）灌丛', '扁刺蔷薇（Rosa sweginzowii）灌丛',
       '杜鹃（Rhododendron simsii）灌丛', nan,
       '绿萼梅（Prunus mume f. viridicalyx）灌丛',
       '川西白刺花（Sophora davidii var. chuansiensis）灌丛',
       '冷地早熟禾（Poa araratica）草原', '矮火绒草（Leontopodium nanum ）草原',
       '针茅（Stipa spp.）草原', '早熟禾（Poa spp.）草甸',
       '垫状点地梅（Androsace tapete）垫状植被', '海韭菜（Triglochin maritima）沼泽',
       '叉枝蓼（Polygonum tortuosum）杂类草高寒草甸', '喜马拉雅嵩草（Kobresia royleana）高寒草甸',
       '太白韭（Allium prattii）杂类草高寒草原', '垂穗披碱草（Elymus nutans）高寒草原',
       '独一味（Lamiophlomis rotata）杂类草草甸', '穗三毛（Trisetum spicatum）高寒草原',
       '短穗兔耳草（Lagotis brachystachya）杂类草草甸',
       '波伐早熟禾（Poa albertii subsp. poophagorum）高寒草原',
       '川藏蒿（Artemisia tainingensis）杂类草草原', '丝颖针茅（Stipa capillacea）高寒草原',
       '小叶栒子（Cotoneaster microphyllus）灌丛', '指裂蒿（Artemisia tridactyla）草原',
       '二裂委陵菜（Potentilla bifurca）杂类草草原',
       '青藏大戟(Euphorbia altotibetica)杂类草草原',
       '西藏风毛菊（Saussurea tibetica）高寒草原',
       '火绒草（Leontopodium leontopodioides）草原',
       '青甘韭（Allium przewalskianum ）杂类草草原', '三角草（Trikeraia hookeri）草甸',
       '紫花针茅（Stipa purpurea）+狼毒（Stellera chamaejasme）草原',
       '紫花针茅（Stipa purpurea）草原（含垫状金露梅）', '固沙草（Orinus thoroldii）高寒草原',
       '冻原白蒿（Artemisia stracheyi）草原', '高山嵩草（Kobresia pygmaea）草甸（含垫状金露梅）',
       '笔直黄耆（Astragalus strictus）草原', '藏白蒿（Artemisia younghusbandii）高寒草原',
       '藏沙蒿（Artemisia wellbyi ）高寒草原（含金露梅）',
       '藏沙蒿（Artemisia wellbyi ）高寒草原（含砂生槐）',
       '藏白蒿（Artemisia younghusbandii）高寒草原（含砂生槐）',
       '高山嵩草（Kobresia pygmaea）草甸（含金露梅）', '三刺草（Aristida triseta）草原',
       '蒿（Artemisia spp.）草原', '紫花针茅（Stipa purpurea）草原（含金露梅）',
       '昆仑针茅（Stipa roborowskyi）草原', '镰荚棘豆（Oxytropis falcata）草原',
       '轮生叶野决明（Thermopsis inflata）草原', '披针叶野决明（Thermopsis lanceolata）草原',
       '青藏薹草（Carex moorcroftii）高寒草原(含垫状金露梅)',
       '冰川棘豆（Oxytropis proboscidea）草原', '绢毛蔷薇（Rosa sericea）灌丛',
       '三刺草（Aristida triseta）草原（含砂生槐）',
       '戈壁针茅（Stipa tianschanica var. gobica）荒漠草原',
       '石生针茅（Stipa tianschanica var. klemenzii）草原'], dtype=object)

In [15]:
df = df.loc[:,['ClassName','PR2015','PR2016','PR2017','PR2018','PR2019']]
df

,ClassName,PR2015,PR2016,PR2017,PR2018,PR2019
0,荒漠,30.500000,36.000000,31.833333,31.750000,30.666667
1,荒漠,30.500000,36.000000,31.833333,31.750000,30.666667
2,荒漠,34.500000,40.416667,34.250000,36.416667,37.166667
3,荒漠,33.916667,19.083333,21.416667,22.166667,30.666667
4,荒漠,23.750000,17.416667,14.750000,19.166667,30.666667
...,...,...,...,...,...,...
17206,长芒草（Stipa bungeana）草原,33.500000,46.666667,42.833333,46.250000,30.166667
17207,长芒草（Stipa bungeana）草原,25.083333,34.166667,29.833333,33.500000,22.333333
17208,长芒草（Stipa bungeana）草原,23.916667,32.500000,28.166667,32.083333,21.250000
17209,长芒草（Stipa bungeana）草原,27.166667,36.666667,33.000000,35.416667,24.083333
17210,西北针茅（Stipa sareptana var. krylovii）草原,22.083333,30.000000,26.750000,29.083333,19.583333

In [19]:
result = df.groupby('ClassName').agg({'PR2015':'mean','PR2016':'mean','PR2017':'mean','PR2018':'mean','PR2019':'mean','ClassName':'size'})
result.head()

,PR2015,PR2016,PR2017,PR2018,PR2019,ClassName
ClassName,,,,,,
三刺草（Aristida triseta）草原,30.987903,44.915323,47.760753,43.208333,35.579301,62
三刺草（Aristida triseta）草原（含砂生槐）,33.166667,56.416667,54.000000,49.916667,39.250000,1
三芒草（Aristida adscensionis）草甸,24.125000,35.250000,36.500000,31.291667,29.375000,10
三裂碱毛茛（Halerpestes tricuspis）沼泽,32.750000,52.638889,51.333333,48.416667,35.888889,3
三角草（Trikeraia hookeri）草甸,28.904762,42.035714,44.416667,39.357143,34.095238,7

In [20]:
result.to_csv("tibet_veg_prep.csv")